apiVersion: v1
kind: Secret
metadata:
    name: leda-diecutting-api-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:XH5qAikD2VuRCHxNIC3r7QwCnYDQyVcwAL2ditB2adsqKW3P5DA4goJKRtWPr7C7LQLVnhbrng6azaqp8NTKr+KLAgUuvyhKJCoxbNLhoAO56msRgx1b8zn70dmbKNWJlltRkOQhTkjjotfNkf6EoN2qjKD2T391K2hvd4r/KA==,iv:LoFoTrCj7bLj3P5j4PoZB07GX3KSbbTMi/0/RRT5W6c=,tag:fsA5CZJ7cFDVNLPl8kcabQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:cIQL6zFOocBpdIfwgEwelVTMntETrgifJW7yypQ71FOxTbYPjw6iqs55XLb2sVbqVnLZJcrTk+aJy4tLiTvInQ==,iv:bxvtMfWgTp/00JIXZfK5C+s0Fw50qflOtw0D0KxAf+w=,tag:lm+HWtRk9SvPpYKrpRRZGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NFU2b254a0liSnhIN1FI
            Rk96bmhwTDNhSkc3ZGtubzNhS3FOZjZhaGs4CklVV1BEQ1lnUWpsdk5ESWQvUjRI
            U1V0UFZFNjJhN0VEZkVkNXJ0UkVHR0kKLS0tIE9qMTdtcFU0NXNsSXpLc0FvWnpZ
            NVdkbGhSaHdSTmRWdExwU2w0ZDFpeGMKAn2rNGFSkL7ipg1oU6Wv8mwyadhKekNv
            fpsifWlLsExQ4afiGYTlM8guw18Kw6UkwsOLHA0Wlnput4fIYM0dXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:SxOpLTEe1OvwbcWFAQpmJ99LyYbVh90UF5SrpSdVrrRHcPfSqYUoQFRsP7hBmiC6gXL90xDKzoXoZZoc2mBHJ2fL9KuYnZaIMzz6JF0FwsrSBC6sprcIpUi8ig3gb7NEnpNuNe3swST0fud5SRjqwdzHFa/UjSQSsWAccvk3hCc=,iv:UL94TArpbMPC6wsSxl3+TgUuFLrMcsOfV9j5acOFmhU=,tag:7l2ENysPLktNiiQ21/ZO1g==,type:str]
    version: 3.13.1
