apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:7SCZRvMiWB5mN4nJ3SgkD/E/ceTpByAo0CPmCz+zaSWdwJ6bgsfI2FOmcFTqq58M8xUX2NtOPjFpxfCc67chtRTeXGlNRdC/K276VDtt/0VnLnZQzGtqNZogGqqoiZf7kaOqeypMWy2DGDfOCm+MjV+aVGl1H6W7vsOoY48DOXIx8wWkd4ZlGq1fSX+Yf0zKqUpT1b8i4Un1MBXA1tRcwIUUdxZB6bJ2Qb3gSxNVKTaP,iv:2nDEsdcVIAZlOl5OCyrQ7ZBBmAfwg5lt+v1aP2l4508=,tag:ETGVjWlI3naY1wrp3e/JJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY0hBaU1wRE96MWl6eTdJ
            c0x3Qm16ZFJWZUhENWZhNXhsNS9pdXkrQ1RvCjhBWnF0UnFGV1VaQ3ZoeDRKTlhs
            LzczZ3BPS3Q4VERwdHJ2MStlY0xJM1UKLS0tIExMNnFzSTJueEt6cnN4SmE1K016
            eGVvMW9wb1lUY1NRWlRKaUhhQisrczAK/gj04CLruy3MDEG5sOMfJmD3kNCSlEIO
            GPHHWqZk08er+/JqPr36myP+LOANNPM/HHj/716G7oeaKB9yHBQ0xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:5uWJ+Oagj534xlpUuJbfU3glbwtM/GONr9eZYUjeIlkpta/ZTjf9vrn3IpHr0eyrANInAxuDROkKXFu4VN8zcGyjwydH71X925Zo0gE4WvnbvP3MsFPRL4qSxJs2nw/KL1WCXw/QZ/wPqPPZ4M49aSGuTeaTBlRqx5aNIgw8a7w=,iv:dg5g3O+eDsBwbq7alkaWdflKUqWhBhaBDv1IbhwDtcw=,tag:xrNznLi9+OEeXT4hR0E9oA==,type:str]
    version: 3.13.1
