apiVersion: v1
kind: Secret
metadata:
    name: leda-diecutting-api-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZkWubbHajIWuHuFY9NJpjg73F9VXL7f6RHMsUSgLLJYUatEgM1Rx7j+ay732k/qPF3+D+evTDs67TJ60LsMe2wDgy+9JjuKzZrEJJdO/+Qb1R1MA0hSHnFSWKKki4lq3WpvVJ4p7zPb9Cg7Mi4mFUgX+k7xETLZkngEQyEY=,iv:d5IAY+DXezZ/9fP1BmC3xr1zDI95jof4PKXuk0EiYyI=,tag:ot0gpoTl0zqufrz6Hmr39A==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:eKT76mfgIl7yrPFJCQTFnaRhSIcuebDWLZct3BykX24IHYe0PwcHayiwIn4G13Nx0hdIK9tZuMRGhzTTDEfVZw==,iv:SLUa8pRaIwISAtrSANG8o+juu4iGxt8XphRMFW82gcU=,tag:IHBlRx+A/vEsBNFuCwsGmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcDdHMGVBeHpScitjSksr
            SzdodjhTbk1adXpnR1pGRnllc216dVFDMDNVCm5CVGZKZFIvZ2l3N1dVZXBiNUFa
            V0FlNWJ6UEg0UG1CSTN2MC9oU0lLeHcKLS0tIHB0b0svdkJ1RlVBRURjM25teGV6
            b1I3WFBvclRwaUM1N01CL0NVb1haZ0kKkXJ2Xx6JoylzVWol6usY9GXWN2AAB/2b
            Yu1+gAVGIZ0YcqT8w+GBMiuBIeUMdmbKlWVFc2GewDiPJOqvyXHw+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:PiJ8meAxWiSkpIxt9/TnTJq9RnJfJPhyHLK+1/11ZY+aPmMBYse5q/+U24NTMs2QNvXsYuB+pM6nvXdxW1Ms6OcI8f4UpqB5nN2ydg8pBOHkKe5PfC6WmGXrdn8io8ThAeQWNz/TKiAncFCVWm/43YuB8a+RxrzLhgIVfilS/ts=,iv:EJr0MjK0AK9Bup2T00b+etngKLC9CD13LbdCBnJ/i/M=,tag:U70h3QcKseGLZLxYi1dlXA==,type:str]
    version: 3.13.1
