apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ZS6QamioUzRsRLDM/hzuoRDBpWFRapSsn8gVdmeNwIuIgQ1fSYUtf38Fr2vpFmrS9o0Lp6GYKERhHPWvVQvBrmyW8fzNKpDaH7Z9dxz//Vc6qphKsSq8FDjksEXGqkjfNOQxPWJCK6LVKkEE5uqinQ8p0rWDmB5LK3vWkQE7bIEwCwCHrQ9goJyveZrlLbhZcJxXQDyyQ2ca+YkdApu02ivNRJdz0rdtVKBIFWMXOKHR,iv:njR6K51CdjH0JYp7VsTVUI4h/SAJUQ3bsw8TjhbuwDM=,tag:WlzQHCxckseMrn4rc2rWaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocFUrYTh0UDlEbDVhc2h4
            a3owMHlXTldYUjBXdW5RWEhGdDZoeXlTVjJNCjQyYnZWVUN1QUV3bWEvT3pZV1FH
            V1M2dmdQa0R6KzdwQ25vbUt4c2l6clkKLS0tIEdrTW5BM3didGlBS2RNYW5WWUh0
            QzNnQXNOazlwcVYxcjF3OEdnRk5WeGcKDeNIr5eXHZJOulXhGdze51BHHHBScNSy
            IuiTtfkOYIMaluQj/q5GlaBDJ1aIGfMt010Kq6d6tT3YyjoghQUz0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:2Vgl8Bp30tQ8EZaeAXXdXMSlJSy+WwLXSPfWG5N2gutCDn6/Oy/BIjr+chENUxsAA9g6PyFeV/jcbRabZBLxIlhSu/GVjPtlGPySoVevXI1+IKCJt9g+bEpmwdX9Ttv3JiADUQNQsKd0NLPJLi/3xykwy5yqUUhm/ffuWBGdM/w=,iv:+shQWKgMp5ccLlwaMeMDx15Bk0bUn61qzKMEXc56sm4=,tag:bXwOaGouPLRq3lU07XOMGQ==,type:str]
    version: 3.13.1
