apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-web
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:792qA3qepYbFuKukc7LhdB8E1T7xuGcQs0BVlL4LLm+JdvOgzLlffKc+j4c9Pdk6fncvv2OW8+gM4Q4QRHPNK0gX4MmLZUxQ60TrklYh88q1h9Bxl7bAOSLKBYc5U4/6/ca7maJl+/l1pNUE1VE5tDVfokTqcw27YaKGRVwms62WranwK36KzGu4LNNqW1vm910I4nmR5DmIESvCJWc6okzP+VUYHCHojQ9TuNpSBg73,iv:H/aHdI2psRfdaPHgldMbz4vAavG+mGGv0bYGMhJeHik=,tag:ckDcDxAxZ8vXKdhrv0JDag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHJ6d215YzY3c3VyVkFP
            QWMxcG9qdnpUY1JTWmdwUDVWeXFRblQ2QVFFCk81bnFwNGl5dVhmUmROaTZXcUpK
            blR5dWtwWmxrc2hITkZ3cy9oOTNhTDgKLS0tIFRIZk1tV09ZRkRGdDNOZzdxN3ZS
            REwvbURxYzU3NEx5NUZiL1RaTWhjT28KTmUde+Qnuhm2uEDjD23o17WGfMM+id9C
            gNx8FyCt0+7Pix9OSV29tywRWQhXFgY4epYLDrcIiljInJ7HWys9Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:48:54Z"
    mac: ENC[AES256_GCM,data:hAnwox/6ex1jGqshd3mBwBUXLKzQHijlvITPTiZ3F8r/nikIvSeBbwRxmOVcntFlFKIMDdezphNQnf4CHhOaF/PV2IMGvMZz3dDQKPGFWOi1QdqHKca0Br+yQnvcppt0ufSy/nlpWnoa3I5XEQOI561ai2AvDwlMSlZHzanymkE=,iv:t6iOb7G4FQfpZfjgewYcI1Ryb7gFOmR+qze1eBSOIns=,tag:TA9CZoc/YX4w38MU9evkQQ==,type:str]
    version: 3.13.1
