apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+m80mWOAj7i3xkudW5yV8pGWw9lWKPrsUBpoNO/8k+S1kw9WfQ67vMRzvhlzgZFX9KuPP3zUe27XLKTWiD1m7Ds5z4vBKwg6oJJBnFS23m+x0jeJZMDKWkevExbfCn/+krhjL0emjRzGZIrfnDJc7KVQ3HwdHnmKHFyxSDD1gRRllrewuiw/G5KgDpcqiRwZMx4zYGlVRpYqMDPywWF3v4E1Hy6xf/4+93pjh8UlGs1p,iv:vDnxlJMxJ06+dycDsaTYl7PulRE9zZJp3m1iqtWJo98=,tag:W99SrnR+9kcBSI7jjyoiAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZitEOFMrWkxNRkRiNmg5
            NW9NajVqMC9UWWpkVEQ3YWZRUVBiWDljZlc0ClVWZ2dqdjRMWWVGaHNwcVhqNUlM
            Qk4wM1Z6VFBiVTJZbFBTWWppZHRxQXMKLS0tIFRyV3JraWVxbDJkUlF5bE5HVDVS
            dHFjWW1JOENncE5TaFF0UWE2aHZyYXMK2njkX3N0BbF7ds9spLJ6WkfM4itqCDjN
            Vw24aDzpndZB+NLnioNUDEObL0M5CfqBN3u/ngoH1ZZz3Kg0Zbo7Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:QwysXglD3K+N+kXCXfRJf1bLvaaWeG4u+lA55rPRJJMFmnkryCQ4NdFJq73dO0s7smqs6xJiJfoWZLe3U3ZGxZZIKG7+HGw9RWg25JQlI55jTGnOpqsNWU1e3tSdZf5b7efNtiT2WXOXRU3X8fZAeoLVJyj4Z1cjcuyc2Rn0sDo=,iv:P1yH3o58bD5WqL9MfcA04pala0b+ygZWOVSlIN59d+8=,tag:GamYAVVc4uEwkpFe6iqJVg==,type:str]
    version: 3.13.1
