apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:AC9zm0mO7fjAdUOc2TuxUK6vAhGFZHQkYmFUbjhXa4JxtUPmOafNvXXGuFv1Jzqs6mRhDir5ipLKcABB15NChkeh3gT8lyGZ7l2QPeLfdm9aehe6fkPTsWZ8U5A1fV8ED61Ii2DD9WArI2efbnVeGiiPdIT7UoOZ8Xwgm2OrbOoAtaSuGdXjtlXYgLP6I6bKspKktGPziy8jPZUv5SlgE4pSkAzsrrpOHbpA6TaP0Jl3,iv:G7M/lmyNaDvkBtQEJo5nVdTj5liFvjJQrz+nX00Wh4c=,tag:4Er3YrDdDVwiqlrQR7beeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzajkxeHptWU5DRzNnOFFQ
            U0tNcXVraVZKWVkxTHBZenJCL0ZDOXg0dmxnClNzeTJqNkdEZFAvNVJxWkpJRzJi
            UUJJUkxWMit3V09na3E2dzY3VUJsUVkKLS0tIFB1N09xcDlqZlpJMUtFdkVTczhl
            VWQ2N1UxcXpUUzF5Qm5meW9GMmZWU2MK/HrPmm45C/14k0YQGAqznd/Hs8+13Wp3
            qghf4/RBpSwy6s/aeajuE3kuZfzIiooNzhBjfu3urkDG3LnYwi5qVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:47:31Z"
    mac: ENC[AES256_GCM,data:z5ne08ebC08j0c9BwY6VroKxxQhph1wyQCg6NYtRzTxqtC5WGukn46shjrcLpNSKPBjVkKXk5ZbgRsQx9S7kRlKEW6ddcepgCY6pNzi3j298lExKF2NvA/65K3mV6Bu2ie8P+8g0zRhqNco6IdFi4zdigpbRHEdXPt261NmXswo=,iv:StbpFJ7Se1EA+TlMtBDsRR6QO9IfqKJXyXB9yiuEZVo=,tag:uVav6xu9C+Wguo8ODbe9cg==,type:str]
    version: 3.13.1
