apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-web
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:H9C9N52XT8x1R/2304K8Ak5aDU02nWglRX1Ywxtz1KBrzrUXRCYzz023qDeqN8dQucbBiHPiksQmZAsXglUYKHguT1zy0l5edONIFwzGoRoOpPQVyCZNTAtsWN4jzWOiNpr7EubhsMqC81KlfVUGiXIJ7oWCjCe3r+tQJI8+pF9RdmPG5Wr+MXI0m02gnjkgOiDSES7ZmSqLoD3HBinubOGjFQ5TLrAv2fuTnEwZDkVL,iv:xWMaVMkAijjvn/b/+2XwfV/3UeNT1K8DwUYRaKkmMHY=,tag:4RNQVWnRMkr2PUyYEwg+Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLekdodUlmNHF2V09FQk5s
            ZUVsd3M2ZWxZMTNUM2xKdE1QSUVMVERJb3pjCjVEUExJT1JnWEo3bzhwdnRuQ1Vw
            Tnl5RHhrbEgyVC9Gb284U2lYWjJ3MGMKLS0tIGtEaXhvMW9tRnl1b3o5NGw3dnFW
            M1JXTG4wMnhZbnhWUG83WVJ1aGppUlEK/tBiWsQuH0L0moj8PZ7hO/gIZYaVU1yc
            9ki9lbT5av0jeZfrQgOT3ntRPUHWbE9hpaK0NLg/3HcemWyYw1y0OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vdmj37l50h3dev3wqetnwe7sw8wfz0w488ezc5ysqw40h98azfzq2kyq49
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T18:48:54Z"
    mac: ENC[AES256_GCM,data:nidbNm2T4kgyiieMpltikYy+G6eG/BgHJew5Zi1BhYI7FH3KgxchppuvwY4+P7jM3S1aCLOygjv65KLrOk8pn2kPWAz46jBb/KrF6/sIs5v2nwX7ogrDnFCATc7QYmfkn8GfInIxrQwDj6Lp2RgxtErO0mjg+abxg8rzM1nFTSo=,iv:A9HuqCQBhxVJMA/MKVc/3yMmjoYi0YckgI5yMiSF3p4=,tag:ULDXS8EJ4hHNxSPtHOS4HA==,type:str]
    version: 3.13.1
