apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leda-diecutting-fe-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sdsonbay/ledayazilim-diecutting-kubeobjects.git
    targetRevision: main
    path: fe/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: leda-diecutting-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
