apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leda-diecutting-dev

resources:
  - namespace.yaml
  - ../../base

generators:
  - ksops.yaml

configMapGenerator:
  - name: leda-diecutting-api-env
    literals:
      - APP_ENV=dev
      - PUBLIC_BASE_URL=https://dev-api-diecutting.ledayazilim.com
      - CORS_ORIGINS=https://dev-diecutting.ledayazilim.com,http://localhost:8081,http://localhost:19006
      - GUEST_CREDITS=3
      - SIGNUP_CREDITS=15

patches:
  - target: { kind: Ingress, name: leda-diecutting-api }
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev-api-diecutting.ledayazilim.com
      - op: replace
        path: /spec/rules/0/host
        value: dev-api-diecutting.ledayazilim.com

images:
  - name: leda-diecutting-api
    newName: ghcr.io/sdsonbay/ledayazilim-diecutting-be
    newTag: "dev-pending"
