apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: leda-diecutting-web-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/ghcr-pull.enc.yaml
